### ISSUE TITLE
initialising open while lock rotates to close is very bad

### ISSUE THREAD

**Issue by IVI053** [pathim/door_access#2]
Because of threading one can initialise an open command while the lock is actually closing. The lock module will ignore this but the door state we keep is open, even while it's actually locked. This leads to a full lockout because unlocking is not possible in open state; Only latch is triggered which is not effective on a locked door.

Two possible solutions:
1. Do not accept state changes for a given time while the lock module rotates
-or-
2. Track actual progress of the lock module through feedback LED.

IMHO possibility 1 could be a quick fix but 2nd one should be implemented in future.

**Comment by pathim** [comment]
Another possibility:
When opening check if the door actually opens while the latch is activated and if not also issue an unlock command

**Comment by IVI053** [comment]
How about both? But maybe only after three times latching w/o actually opening the door? Like some kind of last resort? I'm not quite comfortable yet with unlocking to solve a state problem...
