### ISSUE TITLE
manual locking from inside leads to outside lockout

### ISSUE THREAD

**Issue by IVI053** [pathim/door_access#3]
We didn't thought about what wouhld happen if someone locks the door using the hand wheel.

In this case as the system think it's in unlocked state because we have no way of recognizing the manual turn by hand. If someone tries to open the door only the latch gets triggered.

It's a similar problem like in #2 but with other perspective and prerequisites

**Comment by pathim** [comment]
Fixed: Trying to unlock three times unlocks
